// Generated by gencpp from file readEMG/EMG.msg
// DO NOT EDIT!


#ifndef READEMG_MESSAGE_EMG_H
#define READEMG_MESSAGE_EMG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace readEMG
{
template <class ContainerAllocator>
struct EMG_
{
  typedef EMG_<ContainerAllocator> Type;

  EMG_()
    : EMG1(0)
    , EMG2(0)  {
    }
  EMG_(const ContainerAllocator& _alloc)
    : EMG1(0)
    , EMG2(0)  {
  (void)_alloc;
    }



   typedef int64_t _EMG1_type;
  _EMG1_type EMG1;

   typedef int64_t _EMG2_type;
  _EMG2_type EMG2;




  typedef boost::shared_ptr< ::readEMG::EMG_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::readEMG::EMG_<ContainerAllocator> const> ConstPtr;

}; // struct EMG_

typedef ::readEMG::EMG_<std::allocator<void> > EMG;

typedef boost::shared_ptr< ::readEMG::EMG > EMGPtr;
typedef boost::shared_ptr< ::readEMG::EMG const> EMGConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::readEMG::EMG_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::readEMG::EMG_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace readEMG

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'readEMG': ['/home/jacob/rosWearableWS/src/readEMG/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::readEMG::EMG_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::readEMG::EMG_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::readEMG::EMG_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::readEMG::EMG_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::readEMG::EMG_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::readEMG::EMG_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::readEMG::EMG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de4f5ec7394cd197be042ac9d31b8b5";
  }

  static const char* value(const ::readEMG::EMG_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de4f5ec7394cd19ULL;
  static const uint64_t static_value2 = 0x7be042ac9d31b8b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::readEMG::EMG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "readEMG/EMG";
  }

  static const char* value(const ::readEMG::EMG_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::readEMG::EMG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 EMG1\n\
int64 EMG2\n\
";
  }

  static const char* value(const ::readEMG::EMG_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::readEMG::EMG_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.EMG1);
      stream.next(m.EMG2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EMG_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::readEMG::EMG_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::readEMG::EMG_<ContainerAllocator>& v)
  {
    s << indent << "EMG1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.EMG1);
    s << indent << "EMG2: ";
    Printer<int64_t>::stream(s, indent + "  ", v.EMG2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // READEMG_MESSAGE_EMG_H
